# Generated by Django 3.0.2 on 2020-02-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='situacao',
            field=models.CharField(choices=[('Cursando', 'Cursando'), ('Reprovado', 'Reprovado'), ('Aprovado', 'Aprovado'), ('Transferido', 'Transferido'), ('Abandonou', 'Abandonou'), ('Recuperação', 'Recuperação')], default='Cursando', max_length=15, verbose_name='Situação'),
        ),
    ]
