# Generated by Django 3.0.2 on 2020-02-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_aluno_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.CharField(choices=[('C', 'Cursando'), ('R', 'Reprovado'), ('A', 'Aprovado'), ('T', 'Transferido'), ('AB', 'Abandonou'), ('RC', 'Recuperação')], default='C', max_length=15, verbose_name='Situação'),
        ),
    ]
